name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint